server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: gccc-usuario-service

  datasource:
    url: jdbc:h2:mem:gccc_usuario
    driver-class-name: org.h2.Driver
    username: root
    password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
